"""Play-balance simulation package.

This package hosts the next generation simulation engine derived from
PBINI.txt configuration and MLB league benchmarks. The modules are
organized for clarity and unit-testability.

This is an early scaffolding of the full engine.
"""

from .config import PlayBalanceConfig, load_config  # noqa: F401
from .benchmarks import (  # noqa: F401
    load_benchmarks,
    park_factors,
    weather_profile,
    league_averages,
    get_park_factor,
    league_average,
)
from .ratings import (  # noqa: F401
    clamp_rating,
    combine_offense,
    combine_slugging,
    combine_defense,
    rating_to_pct,
    pct_to_rating,
)
from .probability import (  # noqa: F401
    clamp01,
    roll,
    weighted_choice,
    prob_or,
    prob_and,
    pct_modifier,
    adjustment,
    dice_roll,
    final_chance,
)
from .physics import (  # noqa: F401
    exit_velocity,
    pitch_movement,
    pitcher_fatigue,
    swing_angle,
    bat_speed,
    power_zone_factor,
    vertical_hit_angle,
    ball_roll_distance,
    air_resistance,
    control_miss_effect,
    warm_up_progress,
    pitch_velocity,
    ai_timing_adjust,
)
from .state import PlayerState, BaseState, GameState  # noqa: F401
from .defense import (  # noqa: F401
    bunt_charge_chance,
    hold_runner_chance,
    pickoff_chance,
    pitch_out_chance,
    pitch_around_chance,
    outfielder_position,
    fielder_template,
)
from .fielder import (
    reaction_delay,
    catch_chance,
    max_throw_distance,
    throw_speed,
    good_throw_chance,
    wild_pitch_catch_chance,
    should_chase_ball,
)
from .offense import (  # noqa: F401
    steal_chance,
    maybe_attempt_steal,
    hit_and_run_chance,
    maybe_hit_and_run,
    sacrifice_bunt_chance,
    maybe_sacrifice_bunt,
    squeeze_chance,
    maybe_squeeze,
)
from .pitcher_ai import (  # noqa: F401
    pitch_rating_variation,
    apply_selection_adjustments,
    objective_weights_by_count,
    select_pitch,
)
from .batter_ai import (  # noqa: F401
    StrikeZoneGrid,
    look_for_zone,
    pitch_identification_chance,
    identify_pitch,
    swing_timing,
    adjust_swing_timing,
    discipline_chance,
    check_swing_chance,
    foul_ball_avoid_chance,
    hbp_avoid_chance,
)
from .substitutions import (  # noqa: F401
    Team,
    pinch_hit,
    pinch_run,
    defensive_sub,
    double_switch,
    warm_reliever,
    replace_pitcher,
    cool_down,
)

__all__ = [
    "PlayBalanceConfig",
    "load_config",
    "load_benchmarks",
    "park_factors",
    "weather_profile",
    "league_averages",
    "get_park_factor",
    "league_average",
    "clamp_rating",
    "combine_offense",
    "combine_slugging",
    "combine_defense",
    "rating_to_pct",
    "pct_to_rating",
    "clamp01",
    "roll",
    "weighted_choice",
    "prob_or",
    "prob_and",
    "pct_modifier",
    "adjustment",
    "dice_roll",
    "final_chance",
    "exit_velocity",
    "pitch_movement",
    "pitcher_fatigue",
    "swing_angle",
    "bat_speed",
    "power_zone_factor",
    "vertical_hit_angle",
    "ball_roll_distance",
    "air_resistance",
    "control_miss_effect",
    "warm_up_progress",
    "pitch_velocity",
    "ai_timing_adjust",
    "bunt_charge_chance",
    "hold_runner_chance",
    "pickoff_chance",
    "pitch_out_chance",
    "pitch_around_chance",
    "outfielder_position",
    "fielder_template",
    "steal_chance",
    "maybe_attempt_steal",
    "hit_and_run_chance",
    "maybe_hit_and_run",
    "sacrifice_bunt_chance",
    "maybe_sacrifice_bunt",
    "squeeze_chance",
    "maybe_squeeze",
    "StrikeZoneGrid",
    "look_for_zone",
    "pitch_identification_chance",
    "identify_pitch",
    "swing_timing",
    "adjust_swing_timing",
    "discipline_chance",
    "check_swing_chance",
    "foul_ball_avoid_chance",
    "hbp_avoid_chance",
    "pitch_rating_variation",
    "apply_selection_adjustments",
    "objective_weights_by_count",
    "select_pitch",
    "Team",
    "pinch_hit",
    "pinch_run",
    "defensive_sub",
    "double_switch",
    "warm_reliever",
    "replace_pitcher",
    "cool_down",
    "PlayerState",
    "BaseState",
    "GameState",

"reaction_delay",
"catch_chance",
"max_throw_distance",
"throw_speed",
"good_throw_chance",
"wild_pitch_catch_chance",
"should_chase_ball",
]
